var EE_courses = [
	"EE302: Introduction to Electrical Engineering",
	"EE306: Introduction to Computing",
	"EE309S: Development of a Solar-Powered Vehicle",
	"EE312: Software Design and Implementation I",
	"EE313: Linear Systems and Signals",
	"EE316: Digital Logic Design",
	"EE319K: Introduction to Embedded Systems",
	"EE411: Circuit Theory",
	"EE325: Electromagnetic Engineering",
	"EE325K: Antennas and Wireless Propagation",
	"EE333T: Engineering Communication",
	"EE334K: Quantum Theory Electronic Materials",
	"EE338L: Analog Integrated Circuit Design",
	"EE339: Solid-State Electronic Devices",
	"EE339S: Solar Energy Conversion Devices",
	"EE341: Electric Drives and Machines",
	"EE347: Modern Optics",
	"EE348: Laser and Optical Engineering",
	"EE351K: Probability and Random Processes",
	"EE351M: Digital Signal Processing",
	"EE360C: Algorithms",
	"EE360F: Intro to Software Engineering",
	"EE360K: Introduction to Digital Communications",
	"EE360P: Concurrent and Distributed Systems",
	"EE360T: Software Testing",
	"EE361C: Multicore Computing",
	"EE361Q: Requirements Engineering",
	"EE361R: Radio-Frequency Electronics",
	"EE362K: Introduction to Automatic Control",
	"EE362G: Smart Grids",
	"EE362Q: Power Quality and Harmonics",
	"EE362R: Renewable Energy and Power Systems",
	"EE362S: Development of Solar-Powered Vehicle",
	"EE363M: Microwave and Radio Frequency Engineering",
	"EE363N: Engineering Acoustics",
	"EE364D: Introduction to Engineering Design",
	"EE364E: Interdisciplinary Entrepreneurship",
	"EE368L: Power Systems Apparatus and Laboratory",
	"EE369: Power Systems Engineering",
	"EE371R: Digital Image and Video Processing",
	"EE374K: Biomedical Electronics Instrument Design",
	"EE374L: Applications of Biomedical Engineering",
	"EE379K: Information Security and Privacy",
	"EE422C: Software Design and Implementation II",
	"EE438: Fundamentals Electronic Circuits",
	"EE438K: Analog Electronics",
	"EE440: Integrated Circuit Nanomanufacturing Techniques",
	"EE445L: Embedded Systems Design Lab",
	"EE445M: Embedded and Real-Time Systems Laboratory",
	"EE445S: Real-Time Digital Sig Proc Lab",
	"EE460M: Digital Systems Design Using HDL",
	"EE460J: Data Science Laboratory",
	"EE460N: Computer Architecture",
	"EE460R: Introduction to VLSI Design",
	"EE461L: Software Engineering and Design Laboratory",
	"EE461P: Data Science Principles",
	"EE461S: Operating Systems",
	"EE462L: Power Electronics Laboratory",
	"EE464H: Honors Senior Design Project",
	"EE464K: Senior Design Project",
	"EE464R: Research Senior Design Project",
	"EE464S: Start-Up Senior Design Project",
	"EE471C: Wireless Communications Laboratory"
];

var M_courses = [
	"M408C: Differential and Integral Calculus",
	"M408D: Sequences, Series, and Multivariable Calculus",
	"M427J: Differential Equations with Linear Algebra",
	"M427L: Advanced Calculus for Applications II",
	"M325K: Discrete Math"
];

var PHY_courses = [
	"PHY303K: Engineering Physics I",
	"PHY103M: Lab for Physics 303K",
	"PHY303L: Engineering Physics II",
	"PHY103N: Lab for Physics 303L"
];
